### ISSUE TITLE
Client hangs if go-mysql-server takes too long to return query results

### ISSUE THREAD

**Issue by ckevin** [dolthub/go-mysql-server#945] opened 2022-04-07 16:57 UTC
I have written very simple implementations of Database and Table/Partition so that I can use go-mysql-server as a MySQL frontend to a custom in-house reporting API.  Each Table corresponds to a particular report specification.  The design at present lazily fetches the report schema from an API when Schema() is called, and lazily runs a backend report when PartitionRows() is called.  And for relatively fast-running reports, it works very nicely!

But I have also run into an issue where various clients (MySQL CLI, Tableau) seem to hang forever if go-mysql-server takes a long time to run a query.  The server is still responsive to new connections & queries, but the client that was waiting on the long-running query never gets the result, and generally has to be killed.  

In my implementation, I have seen this both when PartitionRows is slow (say a backend report takes minutes to fetch the table rows), and when doing information_schema queries (which causes Schema() to be called for all tables, which can take minutes with all the API calls in the current naive implementation.)  I can cache report schemas to make that case faster, but I don't have any way to avoid medium-to-long-running reports.

Do you have any ideas for why the clients would never get their query results in these cases?

**Comment by zachmu** [comment] 2022-04-11 17:20
We haven't seen this with long-running queries, no. But we also run our server with the same network timeout as mysql, 1 day. Is the client timing out and never getting signaled that the connection died?

If you can get us a way to repro this we'll look into it.

**Comment by ckevin** [comment] 2022-04-14 02:21
I don't have a simple isolated repro that I can share yet -- but anecdotally, I have found that the issue may be related to my using the "main" branch or some feature that has been added since v0.11.0.

I noticed that the version I was having the problem on looks like this:
```
$ cat go.mod | grep go-mysql-server
	github.com/dolthub/go-mysql-server v0.11.0
replace github.com/dolthub/go-mysql-server v0.11.0 => github.com/dolthub/go-mysql-server v0.11.1-0.20220323183818-6e252a8a9532
```

But I was unable to reproduce the issue when using almost identical code on the latest tagged release:
```
$ cat go.mod | grep go-mysql-server
	github.com/dolthub/go-mysql-server v0.11.0
```

The only changes I had to make to get my code to work on v0.11.0 were removing sql.PartitionsToPartitionIter (which doesn't exist yet), and adding an Auth object to the config:
```
 func (t *Table) Partitions(*sql.Context) (sql.PartitionIter, error) {
-       return sql.PartitionsToPartitionIter(t), nil
+       return &partitionIter{t, 0}, nil
 }

+type partitionIter struct {
+       table *Table
+       idx   int
+}
+
+func (i *partitionIter) Next() (sql.Partition, error) {
+       if i.idx == 1 {
+               return nil, io.EOF
+       }
+       i.idx++
+       return i.table, nil
+}
+
+func (i *partitionIter) Close(*sql.Context) error {
+       i.table = nil
+       return nil
+}
```
```
        config := server.Config{
                Protocol: "tcp",
                Address:  "localhost:3306",
+               Auth:     auth.NewNativeSingle("root", "", auth.AllPermissions),
        }
```
So I can use 0.11.0 as a workaround, as shown here, but there still might be an issue in the newer code:
```
[root@127.0.0.1] mysql> select count(*) from <db>.<table>;
+----------+
| count(*) |
+----------+
|      221 |
+----------+
1 row in set (18 min 33.90 sec)
```
```
[root@127.0.0.1] mysql> select count(*) from information_schema.columns;
+----------+
| count(*) |
+----------+
|    62409 |
+----------+
1 row in set (7 min 50.08 sec)
```
The long delays in my implementation are in the following two methods:
```
func (t *Table) PartitionRows(*sql.Context, sql.Partition) (sql.RowIter, error) {
	if t.runTime.IsZero() {
		client := api.GetClient()
		report, err := api.RunReport(client, t.specHash, 0, 1)
...
		t.rows = &sql_rows
		t.runTime = time.Now()
	}
	return sql.RowsToRowIter(*t.rows...), nil
}
```
```
func (t *Table) Schema() sql.Schema {
	if t.schema == nil {
		client := api.GetClient()
		t.updateSchema(client)
	}
	return *t.schema
}
```
Are these reasonable places to have delays?  This seems to work OK on v0.11.0, but if there's a more compatible way to structure the lookups, that would be good to know.  

Note that RunReport can be slow (minutes) but updateSchema is generally just milliseconds or seconds.  However, there may be thousands of tables that each do a schema lookup -- say when an information_schema query is called, which causes everything to be lazy evaluated at once.  I noticed the same client hangs (on non-v0.11.0) in that situation, when no single API method was slow but the cumulative time was long, as when the single PartitionRows API method took a long time.

**Comment by fulghum** [comment] 2022-08-05 23:45
Hey @ckevin, just checking in on this issue since it's been a while since we got back to you. Do you have any updates? Are you still seeing these problems with the tip of main? Any progress on a repro that we can debug through?

**Comment by ckevin** [comment] 2022-08-11 01:27
I haven't taken a look at this in a while -- not since finding that the prior tagged version did not have the issue.  

It might be some time before I have bandwidth to setup a re-test (especially if the issue is still there and I need to create a generic repro that anyone can run.)  Can we leave this open until I have time to verify?

**Comment by zachmu** [comment] 2022-10-07 20:51
Without a way to reproduce this, I'm going to close this out. Please do reopen if you can find a way to reliably trigger this behavior.

**Closed by zachmu** 2022-10-07 20:51 UTC

**Comment by ckevin** [comment] 2022-10-07 22:10
Have you tried to reproduce it at all?  Simply having a long delay in PartitionRows was enough to cause the problem for me on version v0.11.1-0.20220323183818.

**Comment by zachmu** [comment] 2022-10-12 23:21
Hi Kevin,

We haven't seen this in Dolt, where customers have queries that take minutes to hours to run. I don't know what mechanism would be responsible for a client connection that hangs indefinitely. There's a timeout mechanism at the wire-spooling layer that should cause any clients waiting too long to hang up.

If you can get us a clean repro on the main branch (been a while since we released this package), we would be happy to dig in.
